name: Quantcubator
favicon: null
layout_spectrum: 0.91358
typography_spectrum: 0.22083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#c96146'
    - '#8c381e'
    - '#ff8e53'
  brandStrength: 0.19492531777359545
  lightness: 0.9622509658802301
  saturation: 0.24414050159975886
  rhythmicContrast: 0.1711131373886019
purpose: []
