name: Quantcubator
favicon: null
layout_spectrum: 0.62897
typography_spectrum: 0.24423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#c96146'
    - '#8c381e'
    - '#ff8e53'
  brandStrength: 0.25
  lightness: 0.9622509658802301
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
