name: Quantcubator
favicon: null
layout_spectrum: 0.502
typography_spectrum: 0.22674
title: Quantcubator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#c96146'
    - '#8c381e'
    - '#ff8e53'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
